### ISSUE TITLE
Incorrect Encoding

### ISSUE THREAD

**Issue by bitm0de** [CTI-Tim/Masters2021-MCP-101#1]
[https://github.com/CTI-Tim/Masters2021-MCP-101/blob/main/MastersHelperLibrary/MastersHelperLibrary/TCPClientHelper.cs#L153](https://github.com/CTI-Tim/Masters2021-MCP-101/blob/main/MastersHelperLibrary/MastersHelperLibrary/TCPClientHelper.cs#L153)

```cs
byte[] payload = System.Text.Encoding.GetEncoding(1252).GetBytes(temp);  // Codepage 1252 just happens to preserve all 256 bytes  use this ALWAYS for device communication
```

Windows 1252 encoding will fail to encode all 256 Unicode code points for byte values within the 0x80 to 0x9F (hex) range... IANA ISO 8859-1 (Code page 28591) properly encodes all byte values within the 8-bit range (i.e. `Encoding.GetEncoding(28591)`)

You can verify this with the following code:
```cs
Console.WriteLine(System.Text.Encoding.GetEncoding(28591).GetBytes("\x85")[0].ToString("X2")); // 85
Console.WriteLine(System.Text.Encoding.GetEncoding(1252).GetBytes("\x85")[0].ToString("X2")); // 3F = '?'
```

**Comment by CTI-Tim** [comment]
Correct!   string encoding is a complex topic and programmers used to simpl and simpl plus rarely had to even have to think about it as s+ treats a string as a simple array of bytes.   C# brings a new challenge of encoding that programmers need to think about constantly and match to the device they are communicating to.      the 1252 is a common quick answer that many will find on the internet but as you pointed out has a hole in it that will not produce the desired results.   The interesting thing is that you will find a lot of code out there using the codepage 1252 as a "workaround" for encoding difficulties and it's not a complete answer because most c# programmers do not actually communicate with devices that may binary pack data into the string returned.   at that point it's actually a best practice to deal with the bytes returned directly and do not put them into a string object with encoding.

**Comment by ahav-tech** [comment]
If 1252 not being a complete answer is meant as a learning opportunity then maybe that could be stated in the comments to make it clearer.
Otherwise, can it be changed to 28591?

**Comment by bitm0de** [comment]
Bytes should definitely be used without introducing the nuances of strings into the mix. However, certain implementations within the Crestron ecosystem don't provide us the convenience of avoiding strings for binary data, and this is where codepage 28591 would be preferred (i.e. IANA ISO-8859-1 encoding, also known as Latin1). One example would be the RAD/CCD SDK, which forces you to encode data within a string, rather than a collection or array of bytes.

This is where Windows-1252 will fail because it can't properly encode byte values within the 0x80 to 0x9F (hex) range. If you start off with a byte array and encode any of those bytes into a string, it will encode them as '?' (0x3F) similar to ASCII, and then when you decode it back into a byte array you'll end up with different byte values from the original data.

Windows-1252 is Microsoft's version of ISO-8859-1. For more information about the differences between Windows-1252 and 28591, please see here: https://www.i18nqa.com/debug/table-iso8859-1-vs-windows-1252.html#:~:text=ISO%2D8859%2D1%20(also,assigned%20to%20these%20code%20points

**Comment by bitm0de** [comment]
If you were writing code that substituted ASCII text into a command that also mixes in with other bytes (i.e. `"\x80\x00COMMAND:10\xFF"`) then you'd need to use a different strategy if using Windows-1252 encoding. ISO/IEC-8859-1 encoding doesn't suffer from this problem, making it a bit more suitable for this task.

**Comment by CTI-Tim** [comment]
> If 1252 not being a complete answer is meant as a learning opportunity then maybe that could be stated in the comments to make it clearer.
> Otherwise, can it be changed to 28591?

Yes it can,  and I will expand the comments to help clarify.   This library is not meant to be a complete useable solution but instead a teaching and learning aid so it will stay "broken" in its current state but will be expanded lead the student down the path to the codepages and why.

**Comment by CTI-Tim** [comment]
I also do not see a response here that is very valuable.   Unsure why I received it in a notification but it did not show up in this thread.  Will not post their info as it may have been sent privately.

There are instances where you are forced into a string and a collection or array of bytes cannot be used.  the example provided was the RAD/SSD SDK  wants raw data encoded in a string.   This is not the only example of where you have to encode data in the string.        All of these questions and responses are exactly what I wanted to generate as this will help others immensely when they stumble on this issue.

I am going to link this conversation in the comments.

**Comment by bitm0de** [comment]
Thanks Tim, I think these code comments alongside that updated encoding will be best for people learning. A good example tagged with some helpful links like that should prove to be extremely valuable. I can imagine lots of people coming from a SIMPL+ background migrating over to C# and trying to encode binary data in strings using hex literals (i.e. "\x01\x02" -- since this is how you have to do it in SIMPL+). Code page 28591 should work in this case for everything in the range of "\x00" to "0xFF". As you say, there's no perfect encoding, and even 28591 will fail if you start introducing Unicode literals into the strings... Both Unicode encodings can even fail in those cases due to surrogate pairs. This really means that the best thing is to understand what encoding you're dealing with and to realize that char is a 16-bit datatype in C#. (You'd have to manually parse the most and least significant bytes in those cases, assuming you want multi-byte output, and you know what endianness to be using.)
