### ISSUE TITLE
Use ReceiveData return value

### ISSUE THREAD

**Issue by bitm0de** [CTI-Tim/Masters2021-MCP-101#2]
[https://github.com/CTI-Tim/Masters2021-MCP-101/blob/640355005edc0ee72cd330637982cdcee36ee7b6/MastersHelperLibrary/MastersHelperLibrary/TCPClientHelper.cs#L167](https://github.com/CTI-Tim/Masters2021-MCP-101/blob/640355005edc0ee72cd330637982cdcee36ee7b6/MastersHelperLibrary/MastersHelperLibrary/TCPClientHelper.cs#L167)

There is a `myClient.ReceiveData()` call prior to this `TrimEnd()` that should be used to determine how many bytes were received. If 0x00 is a valid end byte in the corresponding packet this will fail as it removes all null bytes.

**Comment by CTI-Tim** [comment]
Correct!  This is a part of the exercises for the students to complete the code and to put in checks and tests  like that to ensure that their code is more stable.
